apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compair.fullname" . }}-redis
  labels:
    {{- include "compair.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "compair.selectorLabels" . | nindent 6 }}
      tier: redis
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "compair.selectorLabels" . | nindent 8 }}
        tier: redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "compair.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-redis
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        command: ["redis-server", "--appendonly","yes"]
        ports:
        - containerPort: 6379
        resources:
{{ toYaml .Values.redis.resources | indent 10 }}
      {{- if .Values.redis.persistence.enabled }}
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "compair.fullname" . }}-redis-pvc
      {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "compair.fullname" . }}-redis
  labels:
    {{- include "compair.selectorLabels" . | nindent 4 }}
    tier: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
  selector:
    {{- include "compair.selectorLabels" . | nindent 4 }}
    tier: redis
