apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ipeersaml.service_name" . }}
  labels:
    app: {{ template "ipeersaml.service_name" . }}
spec:
  replicas: {{ .Values.ipeersaml.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ipeersaml.service_name" . }}
      stage: {{ .Values.stage }}
  template:
    metadata:
      labels:
        app: {{ template "ipeersaml.service_name" . }}
        stage: {{ .Values.stage }}
    spec:
      containers:
      - name: ipeer-saml-cwl
        image: "{{ .Values.ipeersaml.image.repository }}:{{ .Values.ipeersaml.image.tag }}"
        imagePullPolicy: {{ .Values.ipeersaml.image.pullPolicy }}
        env:
        - name: SAML_SETTINGS
          {{- if .Values.ipeersaml.existingSettingsSecretRef }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.ipeersaml.existingSettingsSecretRef.name }}
              key: {{ .Values.ipeersaml.existingSettingsSecretRef.key | default "saml-settings" }}
          {{- else }}
          value: {{ .Values.ipeersaml.settings | quote }}
          {{- end }}
        - name: SAML_LOGOUT_URL
          value: {{ .Values.ipeersaml.logoutUrl | quote }}
        ports:
        - containerPort: {{ .Values.ipeersaml.service.internalPort }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ipeersaml.service.internalPort }}
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ipeersaml.service_name" . }}
  labels:
    app: {{ template "ipeersaml.service_name" . }}
    stage: {{ .Values.stage }}
spec:
  type: {{ .Values.ipeersaml.service.type }}
  ports:
    - port: {{ .Values.ipeersaml.service.externalPort }}
      targetPort: {{ .Values.ipeersaml.service.internalPort }}
  selector:
    app: {{ template "ipeersaml.service_name" . }}
    stage: {{ .Values.stage }}
